services:
  astroneer-server:
    container_name: astroneer-server
    image: astroneer:latest
    ports:
      - "8777:8777/tcp"
      - "8777:8777/udp"
    volumes:
      - /opt/servers/Astroneer/serverdata:/astroneer
    networks: 
      - game_net
    tty: true
    restart: unless-stopped
    environment:
      - TIMEZONE=America/New_York

networks:
  game_net:
    driver: bridge
    name: game_net